[task.build]
description = "Build the project"
command = "go build ."

[task.run]
description = "Run the project"
command = "./shog --content-dir /home/pspiagicw/code/other-projects/blog/repo/content"
depends = [
    "build"
]
